name: Docker Build

on:
  push:
    branches: [main]
    paths:
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: fskemp/ubuntu-ros1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare cache directory
        run: mkdir -p /tmp/.buildx-cache

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          outputs: type=image,name=${{ env.IMAGE_NAME }},push=true
