name: Docker Build

on:
  push:
    branches: [main]
    paths:
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}  
         password: ${{ secrets.DOCKERHUB_TOKEN }}     
         registry: https://index.docker.io/v2/         

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
         context: .
         platforms: linux/amd64                        
         push: true
         tags: |
          fskemp/ubuntu-ros1:latest
          fskemp/ubuntu-ros1:${{ github.sha }}       
